calibrated: 1
equilibrium:
    sign: -1
    signFlexor: 1
    signExtensor: -1
    nameFlexor: "biceps"
    nameExtensor: "triceps"
    servoRange: 6.2832
    servoOffset: 0
signEncoder: 1
signJoint: 1
name: "elbow"
nameEncoder: "elbow_encoder"
minAngle: -0.66
maxAngle: 0.35
maxAbsForwardError: 0.7
gains:
    P: 0.1
    I: 0.0002
    D: 0.2
