controller_list:
  - name: gummi_right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_yaw
      - shoulder_roll
      - shoulder_pitch
      - upperarm_roll
      - elbow
      - forearm_roll
      - wrist_pitch
