horizontal_abductor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: horizontal_abductor
    joint_speed: 100
    motor:
        id: 6
        init: 14333
        min: 0
        max: 26618