upperarm_roll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: upperarm_roll
    joint_speed: 2.5
    motor:
        id: 12
        init: 2048
        min: 0
        max: 4095
