wrist_extensor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: wrist_extensor
    joint_speed: 6.28
    motor:
        id: 23
        init: 512
        min: 0
        max: 1023
